### ISSUE TITLE
pio_disassembler.cpp does not compile on GCC 13.0.1

### ISSUE THREAD

**Issue by arjunak234** [raspberrypi/pico-sdk#1317]
```
/home/user/src/pico-sdk/tools/pioasm/pio_disassembler.h:16:25: error: ‘uint16_t’ was not declared in this scope
   16 | std::string disassemble(uint16_t inst, uint sideset_bits, bool sideset_opt);
      |                         ^~~~~~~~
/home/user/src/pico-sdk/tools/pioasm/pio_disassembler.h:1:1: note: ‘uint16_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
  +++ |+#include <cstdint>
```
