### PR TITLE
Fix missing headers leading to #include failing when pulling in hardware_irq and pico_bootrom

### LINKED ISSUE #1929: Compilation issue after upgrading to 2.0.0 from 1.5.1
I have a project where I have the Pico SDK in a git submodule. I recently tried upgrading the SDK from version 1.5.1 to version 2.0.0, and now I have compilation issues where runtime_init.h isn't found. The following is from running cmake and make in a clean build directory. (I deleted the build directory as instructed in the SDK 2.0.0 release notes.) The error is about 7 lines from the bottom. (`/Users/foo/bar/pico-sdk/src/common/pico_sync/mutex.c:9:10: fatal error: pico/runtime_init.h: No such file or directory`)

```
foo@computer build % cmake ..
PICO_SDK_PATH is /Users/foo/bar/pico-sdk
Defaulting platform (PICO_PLATFORM) to 'rp2040' since not specified.
Defaulting target board (PICO_BOARD) to 'pico' since not specified.
Using board configuration from /Users/foo/bar/pico-sdk/src/boards/include/boards/pico.h
Pico Platform (PICO_PLATFORM) is 'rp2040'.
-- Defaulting build type to 'Release' since not specified.
Defaulting compiler (PICO_COMPILER) to 'pico_arm_cortex_m0plus_gcc' since not specified.
Configuring toolchain based on PICO_COMPILER 'pico_arm_cortex_m0plus_gcc'
Defaulting PICO_GCC_TRIPLE to 'arm-none-eabi'
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/local/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/local/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /opt/local/bin/arm-none-eabi-gcc
Build type is Release
CMake Warning at pico-sdk/tools/Findpicotool.cmake:28 (message):
  No installed picotool with version 2.0.0 found - building from source

  It is recommended to build and install picotool separately, or to set
  PICOTOOL_FETCH_FROM_GIT_PATH to a common directory for all your SDK
  projects
Call Stack (most recent call first):
  pico-sdk/tools/CMakeLists.txt:138 (find_package)
  pico-sdk/src/cmake/on_device.cmake:33 (pico_init_picotool)
  pico-sdk/src/rp2040/boot_stage2/CMakeLists.txt:57 (pico_add_dis_output)
  pico-sdk/src/rp2040/boot_stage2/CMakeLists.txt:101 (pico_define_boot_stage2)


Downloading Picotool
-- Found Python3: /opt/local/bin/python3.12 (found version "3.12.5") found components: Interpreter
TinyUSB available at /Users/foo/bar/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /Users/foo/bar/pico-sdk/lib/btstack
cyw43-driver available at /Users/foo/bar/pico-sdk/lib/cyw43-driver
lwIP available at /Users/foo/bar/pico-sdk/lib/lwip
mbedtls available at /Users/foo/bar/pico-sdk/lib/mbedtls
-- Configuring done (2.0s)
-- Generating done (0.2s)
-- Build files have been written to: /Users/foo/bar/build
foo@computer build % make
[  0%] Creating directories for 'pioasmBuild'
[  0%] No download step for 'pioasmBuild'
[  1%] No update step for 'pioasmBuild'
[  1%] No patch step for 'pioasmBuild'
[  1%] Performing configure step for 'pioasmBuild'
Not searching for unused variables given on the command line.
loading initial cache file /Users/foo/bar/build/pico-sdk/src/rp2_common/pico_cyw43_driver/pioasm/tmp/pioasmBuild-cache-Release.cmake
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/foo/bar/build/pioasm
[  1%] Performing build step for 'pioasmBuild'
[100%] Built target pioasm
[  1%] Performing install step for 'pioasmBuild'
[100%] Built target pioasm
Install the project...
-- Install configuration: "Release"
[  1%] Completed 'pioasmBuild'
[  1%] Built target pioasmBuild
[  1%] Generating rp2040_sdio.pio.h
[  1%] Built target no-OS-FatFS-SD-SDIO-SPI-RPi-Pico_rp2040_sdio_pio_h
[  1%] Built target picotoolForceReconfigure
[  1%] Creating directories for 'picotoolBuild'
[  1%] No download step for 'picotoolBuild'
[  1%] No update step for 'picotoolBuild'
[  1%] No patch step for 'picotoolBuild'
[  2%] Performing configure step for 'picotoolBuild'
Not searching for unused variables given on the command line.
-- The C compiler identification is AppleClang 15.0.0.15000309
-- The CXX compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
.//Users/foo/bar/build/_deps/picotool/
-- Using the single-header code from /Users/foo/bar/build/_deps/picotool-src/lib/nlohmann_json/single_include/
CMake Deprecation Warning at /Users/foo/bar/pico-sdk/lib/mbedtls/CMakeLists.txt:23 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Found Python3: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9 (found version "3.9.6") found components: Interpreter
libUSB is not found - no USB support will be built
-- Configuring done (0.6s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/foo/bar/build/_deps/picotool-build
[  2%] Performing build step for 'picotoolBuild'
[ 67%] Built target mbedcrypto
[ 75%] Built target mbedx509
[ 85%] Built target mbedtls
[ 87%] Built target errors
[ 88%] Built target elf
[ 91%] Built target bintool
[ 93%] Built target elf2uf2
ld: warning: ignoring duplicate libraries: 'errors/liberrors.a'
[100%] Built target picotool
[  2%] Performing install step for 'picotoolBuild'
[ 67%] Built target mbedcrypto
[ 75%] Built target mbedx509
[ 85%] Built target mbedtls
[ 87%] Built target errors
[ 88%] Built target elf
[ 91%] Built target bintool
[ 93%] Built target elf2uf2
[100%] Built target picotool
Install the project...
-- Install configuration: "Release"
[  2%] Performing test step for 'picotoolBuild'
picotool v2.0.0 (Darwin, AppleClang-15.0.0.15000309, Release)
[  2%] Completed 'picotoolBuild'
[  2%] Built target picotoolBuild
[  2%] Building ASM object pico-sdk/src/rp2040/boot_stage2/CMakeFiles/bs2_default.dir/compile_time_choice.S.obj
[  2%] Linking ASM executable bs2_default.elf
[  2%] Built target bs2_default
[  3%] Generating bs2_default.bin
[  3%] Generating bs2_default_padded_checksummed.S
[  3%] Built target bs2_default_padded_checksummed_asm
[  3%] Building C object helpers/CMakeFiles/mutex.dir/__/pico-sdk/src/common/pico_sync/sem.c.obj
[  3%] Building C object helpers/CMakeFiles/mutex.dir/__/pico-sdk/src/common/pico_sync/lock_core.c.obj
[  3%] Building C object helpers/CMakeFiles/mutex.dir/__/pico-sdk/src/common/pico_sync/mutex.c.obj
/Users/foo/bar/pico-sdk/src/common/pico_sync/mutex.c:9:10: fatal error: pico/runtime_init.h: No such file or directory
    9 | #include "pico/runtime_init.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [helpers/CMakeFiles/mutex.dir/__/pico-sdk/src/common/pico_sync/mutex.c.obj] Error 1
make[1]: *** [helpers/CMakeFiles/mutex.dir/all] Error 2
make: *** [all] Error 2
```

Running cmake/build thru visual studio has some different flags but produces similar output except that it gives the error both in mutex.c and time.c.

I'm guessing this is just me goosing up git submodules and/or cmake somehow, but I'd appreciate any guidance.

### PR DESCRIPTION
**Pull request by aabizri**
As suggested by @kilograham (in https://github.com/raspberrypi/pico-sdk/issues/1929#issuecomment-2364746391), add `pico_runtime_init` as well as `pico_runtime` and `boot_picobin_headers` to the `CMakeLists.txt`s defining `hardware_irq` and `pico_bootrom_headers`.

While the issue initially was reported only for `hardware_irq` missing `pico_runtime_init`, the same issue affect the other mentionned.

Fixes #1929

### CODE REVIEW

File: src/rp2_common/pico_bootrom/CMakeLists.txt [hunk 1]
```diff
@@ -8,5 +8,5 @@ target_sources(pico_bootrom INTERFACE
         ${CMAKE_CURRENT_LIST_DIR}/bootrom_lock.c
         )
 
-target_link_libraries(pico_bootrom_headers INTERFACE boot_picoboot_headers boot_bootrom_headers)
+target_link_libraries(pico_bootrom_headers INTERFACE boot_picoboot_headers boot_bootrom_headers boot_picobin_headers pico_runtime_init)
```
Comment (peterharperuk) [inline src/rp2_common/pico_bootrom/CMakeLists.txt:11]: This should possibly be pico_runtime_init_headers rather than pico_runtime_init

Comment (peterharperuk) [reply src/rp2_common/pico_bootrom/CMakeLists.txt]: Thanks!

**Review by peterharperuk — APPROVED** [review]

**Comment by jaymin1328** [comment]
/usr/lib/gcc/arm-none-eabi/12.2.1/../../../arm-none-eabi/bin/ld: cannot find -lboot_bootrom_headers: No such file or directory

I used your changes and  could remove error in compilation but at the time of linking I had the same error

**Comment by peterharperuk** [comment]
> cannot find -lboot_bootrom_headers: No such file or directory

You'll get this if the sdk doesn't know about boot_bootrom_headers, which would indicate you're not using the latest sdk.

**Comment by jaymin1328** [comment]
> > cannot find -lboot_bootrom_headers: No such file or directory
> 
> You'll get this if the sdk doesn't know about boot_bootrom_headers, which would indicate you're not using the latest sdk.

@peterharperuk  I am using SDK git tag 2.0.0 , look the output of `git log` command  


`j@raspberrypi:~/pico/pico-sdk $ git log
commit 2f1d186769a7f070cd2b193d580827c8d75e3e11 (HEAD, master)
Author: jaymin patel <jaymin.1328@gmail.com>
Date:   Tue Nov 5 14:50:51 2024 +0000

    added fixes to work with 2.0.0 from internet didn't working

commit efe2103f9b28458a1615ff096054479743ade236 (tag: 2.0.0, origin/master, origin/HEAD)
Author: graham sanderson <graham.sanderson@raspberrypi.com>
Date:   Thu Aug 8 06:02:04 2024 -0500

    SDK 2.0.0 release

commit 45984e276f85aa24d33aa0ab62ed1e6df96a0784
`

**Comment by peterharperuk** [comment]
Have you deleted your build folder?

**Comment by jaymin1328** [comment]
> Have you deleted your build folder?

Yes!

What I did was setup a RaspberryPi5 with pico_setup.sh and git clone my code and trying to compile 

@aabizri This is my cmakelist.txt

```
cmake_minimum_required(VERSION 3.15)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(PICO_BOARD pico)
set(CMAKE_BUILD_TYPE Debug)
# Set the Pico SDK path if not already set
# set(PICO_SDK_PATH "/path/to/pico-sdk")

# Pull in Raspberry Pi Pico SDK (must be before project)
include($ENV{PICO_SDK_PATH}/pico_sdk_init.cmake)

# # Project node -----------------------------------------------------------------------------------------
# set(PROJECT_NODE node)
# project(${PROJECT_NODE} C CXX ASM)
# pico_sdk_init()

# # Include subdirectories for the node project
# add_subdirectory(sensors/SCD41)
# add_subdirectory(sensors/AS7331)
# add_subdirectory(sensors/BME688)
# add_subdirectory(sensors/ICS43434)
# add_subdirectory(sensors/ONEWIRE)
# add_subdirectory(sensors/dht)
# add_subdirectory(sensors/VEML7700)
# add_subdirectory(sensors/STHS34)
# add_subdirectory(sensors/SENSIRION)
# add_subdirectory(sensors/multiSensor)
# add_subdirectory(CAN)
# add_subdirectory(SEREEPROM)
# add_subdirectory(CMD)
# add_subdirectory(FS)
# add_subdirectory(FS/littlefs-lib)
# add_subdirectory(FS/stdinit-lib)
# add_subdirectory(WIZNET)
# add_subdirectory(SEGGER)
# add_subdirectory(MQTT_LWIP)

# add_executable(${PROJECT_NODE} main_node.cpp)

# target_include_directories(${PROJECT_NODE} PRIVATE ${CMAKE_CURRENT_LIST_DIR})

# pico_set_program_name(${PROJECT_NODE} "${PROJECT_NODE}")
# pico_set_program_version(${PROJECT_NODE} "0.1")

# pico_enable_stdio_uart(${PROJECT_NODE} 0)
# pico_enable_stdio_usb(${PROJECT_NODE} 1)

# target_link_libraries(${PROJECT_NODE} PRIVATE
# pico_stdlib
# # pico_runtime_init
# # pico_runtime_init_headers
# # pico_runtime
# # boot_picoboot_headers
# # boot_bootrom_headers
# # boot_picobin_headers
# # pico_runtime_init_headers
# hardware_rtc
# hardware_i2c
# hardware_spi
# segger
# SCD41
# AS7331
# BME680
# VEML7700
# STHS34
# MIC
# pico_one_wire
# CAN
# EEPROM
# CMD
# littlefs-lib
# stdinit-lib
# FS
# SENSIRION
# BME680
# multiSensor
# )

# pico_add_extra_outputs(${PROJECT_NODE})

# Project gateway --------------------------------------------------------------------------------------
set(PROJECT_GATEWAY gateway)
project(${PROJECT_GATEWAY} C CXX ASM)
pico_sdk_init()

set(CMAKE_C_FLAGS_DEBUG "-Og -g")      # Debugging info with some optimization
set(CMAKE_CXX_FLAGS_DEBUG "-Og -g")    # C++ Debug flags

# Include subdirectories for the node project
add_subdirectory(sensors/SCD41)
add_subdirectory(sensors/AS7331)
add_subdirectory(sensors/BME688)
add_subdirectory(sensors/ICS43434)
add_subdirectory(sensors/ONEWIRE)
add_subdirectory(sensors/dht)
add_subdirectory(sensors/VEML7700)
add_subdirectory(sensors/STHS34)
add_subdirectory(sensors/multiSensor)
add_subdirectory(CAN)
add_subdirectory(SEREEPROM)
add_subdirectory(CMD)
add_subdirectory(FS)
add_subdirectory(FS/littlefs-lib)
add_subdirectory(FS/stdinit-lib)
add_subdirectory(WIZNET)
add_subdirectory(SEGGER)
add_subdirectory(MQTT_LWIP)

add_executable(${PROJECT_GATEWAY} main_gw.cpp)

target_include_directories(${PROJECT_GATEWAY} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

pico_set_program_name(${PROJECT_GATEWAY} "${PROJECT_GATEWAY}")
pico_set_program_version(${PROJECT_GATEWAY} "0.1")

pico_enable_stdio_uart(${PROJECT_GATEWAY} 0)
pico_enable_stdio_usb(${PROJECT_GATEWAY} 1)

target_link_libraries(${PROJECT_GATEWAY} PRIVATE
        pico_stdlib
        #pico_runtime_init
        hardware_spi
        hardware_i2c
        hardware_dma
        hardware_adc
        hardware_pio
        hardware_clocks
        pico_multicore
        CMD
        CAN
        segger
        STHS34
        AS7331
        EEPROM
        FS
        littlefs-lib
        stdinit-lib
        MIC
        dht
        TEGMQTT
        BME680
        VEML7700
        multiSensor
)

pico_add_extra_outputs(${PROJECT_GATEWAY})

```

**Comment by jaymin1328** [comment]
> I'm not able to reproduce the linking error. `boot_bootrom_headers` should not even be involved in linking as it's an `INTERFACE` library.
> 
> This looks like the CMake definition of `boot_bootrom_headers` is not being reached, which should not happen as `rp2_common.cmake` adds the relevant subdirectory in the same way as any other required for building.
> 
> Are you (@jaymin1328) calling `pico_sdk_init` as required ? Did you clear the CMake cache/build directory since the upgrade to `2.0.0` ? Do you have a code reproduction to share ?

@aabizri Here is the full code . I am trying to build `BOTH` folder 
[BOTH.zip](https://github.com/user-attachments/files/17666524/BOTH.zip)

**Comment by peterharperuk** [comment]
@jaymin1328 Make sure you have these two commits (the fix for this defect) in pico-sdk. Your code builds for me.

bc8ded18 (HEAD -> fix-missing-interface-links) Adjust targets being included
49a2a01c Fix compilation issues when including in hardware_irq and pico_bootrom (#1929)

**Comment by jaymin1328** [comment]
> @jaymin1328 Make sure you have these two commits (the fix for this defect) in pico-sdk. Your code builds for me.
> 
> bc8ded18 (HEAD -> fix-missing-interface-links) Adjust targets being included 49a2a01c Fix compilation issues when including in hardware_irq and pico_bootrom (#1929)

Thanks a lot for the help!
However, I could not see the commits in my local repo 

```
j@raspberrypi:~/pico/pico-sdk $ git log --format="%h" | grep bc8ded18
j@raspberrypi:~/pico/pico-sdk $ git log --format="%h" | grep 49a2a01c
```

can you send me the links of the commits like this one ?
[https://github.com/raspberrypi/pico-sdk/pull/1956/commits/29b1fa99382cd512021f3773fcf2a97a85efd226](url)

**Comment by peterharperuk** [comment]
The changes are in this PR - see the commit tab...

https://github.com/raspberrypi/pico-sdk/pull/1956/commits/29b1fa99382cd512021f3773fcf2a97a85efd226
https://github.com/raspberrypi/pico-sdk/pull/1956/commits/56efb281b00e93c718492287cdf3e063fa36fafb

**Comment by jaymin1328** [comment]
> The changes are in this PR - see the commit tab...
> 
> [29b1fa9](https://github.com/raspberrypi/pico-sdk/commit/29b1fa99382cd512021f3773fcf2a97a85efd226) [56efb28](https://github.com/raspberrypi/pico-sdk/commit/56efb281b00e93c718492287cdf3e063fa36fafb)

Error still persists ...
After incorporating changes mentioned in 56efb281
[CMakeOutput.log](https://github.com/user-attachments/files/17677900/CMakeOutput.log)
[make.log](https://github.com/user-attachments/files/17677902/make.log)


After incorporating changes mentioned in 29b1fa99
[CMakeOutput.log](https://github.com/user-attachments/files/17677925/CMakeOutput.log)
[make.log](https://github.com/user-attachments/files/17677927/make.log)


Also you mentioned first `bc8ded18` and `49a2a01c`
and now you mentioned second time `29b1fa99` and `56efb281`

Are they both same things or am I seeing things wrongly ?

**Comment by peterharperuk** [comment]
@kilograham Can I merge this. This build issue seems to be causing confusion.

**Comment by aabizri** [comment]
@jaymin1328 The pull requests proposes to merge the two commits specified by @peterharperuk and that you said you incorporated. ([29b1fa9](https://github.com/raspberrypi/pico-sdk/commit/29b1fa99382cd512021f3773fcf2a97a85efd226) [56efb28](https://github.com/raspberrypi/pico-sdk/commit/56efb281b00e93c718492287cdf3e063fa36fafb)).

Without the changes in this pull request, both the master (latest 2.0.0) & develop (tip) branch of this repository are succeptible to issue #1929. Indeed, some targets (let's call them **A** (1)) defined by the SDK should have header-only dependencies on targets (which we'll call **B** (2)), but don't, leading to missing headers when compiling. This is the symptom of the issue solved by the current PR. 

This doesn't happen all the time, as depending on how the downstream target **C** (3) configured the include directories & targets, even when **A** is added as a dependency, it is possible for the required targets **B** to have been also added as a depdency otherwise, leading to no error in compilation as the headers can then be found.

If you are hitting the issue as specified in the description of this PR and/or issue #1929, and until this is fixed upstream in `develop` and then released in `master`/`2.1.0`. I recommend either using the branch of the pull request (4) or applying the workarounds in issue #1929, which are essentially to `target_link_libraries(C PRIVATE A B)` where today you do `target_link_libraries(C PRIVATE A)`.

(1): `hardware_irq`, `pico_bootrom`
(2): that is, other targets whose headers are required for the aforementioned targets
(3): in your posted `CMakeLists.txt`, that is the one producing `gateway.elf`
(4): on my fork, branch `fix-missing-interface-links`: https://github.com/aabizri/pico-sdk/tree/fix-missing-interface-links

**Comment by jaymin1328** [comment]
> @jaymin1328 The pull requests proposes to merge the two commits specified by @peterharperuk and that you said you incorporated. ([29b1fa9](https://github.com/raspberrypi/pico-sdk/commit/29b1fa99382cd512021f3773fcf2a97a85efd226) [56efb28](https://github.com/raspberrypi/pico-sdk/commit/56efb281b00e93c718492287cdf3e063fa36fafb)).
> 
> Without the changes in this pull request, both the master (latest 2.0.0) & develop (tip) branch of this repository are succeptible to issue #1929. Indeed, some targets (let's call them **A** (1)) defined by the SDK should have header-only dependencies on targets (which we'll call **B** (2)), but don't, leading to missing headers when compiling. This is the symptom of the issue solved by the current PR.
> 
> This doesn't happen all the time, as depending on how the downstream target **C** (3) configured the include directories & targets, even when **A** is added as a dependency, it is possible for the required targets **B** to have been also added as a depdency otherwise, leading to no error in compilation as the headers can then be found.
> 
> If you are hitting the issue as specified in the description of this PR and/or issue #1929, and until this is fixed upstream in `develop` and then released in `master`/`2.1.0`. I recommend either using the branch of the pull request (4) or applying the workarounds in issue #1929, which are essentially to `target_link_libraries(C PRIVATE A B)` where today you do `target_link_libraries(C PRIVATE A)`.
> 
> (1): `hardware_irq`, `pico_bootrom` (2): that is, other targets whose headers are required for the aforementioned targets (3): in your posted `CMakeLists.txt`, that is the one producing `gateway.elf` (4): on my fork, branch `fix-missing-interface-links`: https://github.com/aabizri/pico-sdk/tree/fix-missing-interface-links

Thanks a lot for the detailed explanation. I will try your branch and let you know.

File: src/rp2_common/hardware_irq/CMakeLists.txt [hunk 2]
```diff
@@ -4,7 +4,7 @@ pico_simple_hardware_target(irq)
 
 target_sources(hardware_irq INTERFACE ${CMAKE_CURRENT_LIST_DIR}/irq_handler_chain.S)
 
-target_link_libraries(hardware_irq INTERFACE pico_sync) # not mirrored as only implementation requires it
+target_link_libraries(hardware_irq INTERFACE pico_sync pico_runtime_init_headers pico_runtime) # not mirrored as only implementation requires it
```
Comment (kilograham) [inline src/rp2_common/hardware_irq/CMakeLists.txt:7]: why is `pico_runtime` here?

**Comment by kilograham** [comment]
> @kilograham Can I merge this. This build issue seems to be causing confusion.

I had glanced at this a couple of times, but change looked a bit weird and didn't dig in further, I have made a comment

File: src/rp2_common/hardware_irq/CMakeLists.txt (hunk 2 above)
Comment (peterharperuk) [reply src/rp2_common/hardware_irq/CMakeLists.txt:7]: Presumably because of this?
```
/home/peterh/source/pico2/pico-sdk-rp2350/src/rp2_common/pico_runtime_init/include/pico/runtime_init.h:11:10: fatal error: pico/runtime.h: No such file or directory

   11 | #include "pico/runtime.h"

      |          ^~~~~~~~~~~~~~~~


```

Comment (kilograham) [reply src/rp2_common/hardware_irq/CMakeLists.txt:7]: yeah; i was concerned about it pulling in `pico_runtime`, but yeah `pico_runtime_init_headers` should pull in `pico_runtime_headers`

**Comment by kilograham** [comment]
superseded by #2031
