### PR TITLE
Fix flash_cs_force

### PR DESCRIPTION
**Pull request by will-v-pi**
The picotool CI build of pico-examples was failing with this error:

```
/home/runner/work/picotool/picotool/pico-sdk/src/rp2_common/hardware_flash/flash.c: In function 'flash_do_cmd_cs':
/home/runner/work/picotool/picotool/pico-sdk/src/rp2_common/hardware_flash/flash.c:299:23: error: conversion from 'uint' {aka 'unsigned int'} to 'uint8_t' {aka 'unsigned char'} may change value [-Werror=conversion]
  299 |     flash_cs_force(0, cs);
      |                       ^~
```

This was broken by https://github.com/raspberrypi/pico-sdk/pull/2919/changes/15fd99682fcc65bc0f4cf779bafd4e48b2f8366d which updated `flash_do_cmd_cs` to take a `uint` but left `flash_cs_force` expecting a `uint8_t` - this fixes that

### CODE REVIEW

**Review by kilograham — APPROVED** [review]
hmm i thought i had fixed that, but i think i redid the pr manually in a different branch l-)
